name: SocialMedia
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

# A description of the library this package provides.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
